### ISSUE TITLE
No-one currently at Sanger is a contributor for this project any more

### ISSUE THREAD

**Issue by tcutts** [wtsi-ic/wtsi-software-policy#8]
Josh, if you happen to see this, can you make me a contributor, please?

**Comment by mcast** [comment]
Hi Tim,

https://github.com/orgs/wtsi-ic/people says @vviyer can do the same things.

Is it time to use something like https://github.com/bewt85/GithubConglomerate to prevent this kind of problem before it happens again?

hth,

m
